### ISSUE TITLE
product-list.component.html

### ISSUE THREAD

**Issue by VZhyrytskiy** [capitanPink/AngCourseShop#3]
<app-product [name]="product.name"
                 [price]="product.price"
                 [description]="product.description"
                 [category]="product.category"
                 [isAvailable]="product.isAvailable">
    </app-product>
Не нужно передавать свойства объекта, как отдельные инпуты. Много кода в шаблоне, много кода в классе. Лучше передайте один инпут объект product

**Comment by capitanPink** [comment]
@VZhyrytskiy Done, thank you!!
